### ISSUE TITLE
How did you successfully declare a dependency on sc.fiji:Trainable_Segmentation?

### ISSUE THREAD

**Issue by aubreyyan** [schmiedc/pHluorinJ#2]
When I try to declare a dependency on `Trainable_Segmentation`, I get the following error `Could not find artifact sc.fiji:Trainable_Segmentation:pom:3.2.33 in central (https://repo.maven.apache.org/maven2)`

![image](https://user-images.githubusercontent.com/60039494/142946791-159eaf8e-29ce-4120-ad69-1fb9e437eea1.png)

Are there any unique steps you had to take to make the dependency resolution go through?

Thanks

**Comment by schmiedc** [comment]
Trainable weka segmentation is not supplied via maven central.
It comes via scijava:

https://imagej.net/develop/maven#repositories
